name: Build and Push Custom Component

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install hatch

    - name: Set version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        hatch version $VERSION
    
    - name: Build and push
      env:
        API_KEY: ${{ secrets.DEEPSET_CLOUD_API_KEY }} # Make sure to add this secret to your repository
      run: hatch run dc:build-and-push
